# Generated by Django 5.1.2 on 2024-10-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserClient',
            new_name='User_client',
        ),
    ]
