# Generated by Django 4.2 on 2024-10-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_admin_name_reservation_checkout_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='admin_name',
        ),
    ]
