# Generated by Django 4.2 on 2024-10-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('horaire', models.CharField(help_text="Horaires d'ouverture, par exemple: 09:00 - 18:00", max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, help_text='Coût en euros', max_digits=10)),
                ('evaluation', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, help_text="Image de l'activité", null=True, upload_to='images/activites/')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
            },
        ),
    ]
