# Generated by Django 5.1.2 on 2024-10-30 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('note', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('date_analyse', models.DateTimeField(auto_now_add=True)),
                ('avis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentiment.avis')),
            ],
        ),
    ]
