# Generated by Django 5.1.2 on 2024-10-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='destination',
            field=models.CharField(default='destinationpar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avis',
            name='utilisateur',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
