# Generated by Django 5.1.2 on 2024-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0002_avis_destination_avis_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesentiment',
            name='sentiment',
            field=models.CharField(max_length=50),
        ),
    ]
