# Generated by Django 5.1.2 on 2024-10-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0003_alter_analysesentiment_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesentiment',
            name='avis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='sentiment.avis'),
        ),
    ]
