# Generated by Django 5.1.2 on 2024-10-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_alter_analysesentiment_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysesentiment',
            name='avis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sentiment.avis'),
        ),
    ]
