# Generated by Django 5.1.2 on 2024-10-29 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TexteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue_source', models.CharField(help_text="Langue du texte source (par exemple, 'fr' pour français)", max_length=50)),
                ('contenu', models.TextField(help_text='Contenu du texte à traduire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TexteTraduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langue_cible', models.CharField(help_text="Langue cible de la traduction (par exemple, 'en' pour anglais)", max_length=50)),
                ('texte_traduit', models.TextField(help_text='Contenu du texte traduit')),
                ('date_traduction', models.DateTimeField(auto_now_add=True)),
                ('texte_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions', to='traductions.textesource')),
            ],
        ),
    ]
